package nightgames.skills;

import nightgames.characters.Character;
import nightgames.characters.NPC;
import nightgames.global.DebugFlags;
import nightgames.pet.Ptype;

import java.util.HashSet;
import java.util.Set;

/**
 * TODO: Write class-level documentation.
 */
public class SkillPool {
    public static Set<Skill> skillPool = new HashSet<>();
    static {
        SkillPool.buildSkillPool(NPC.noneCharacter());
    }

    public static void buildSkillPool(Character ch) {
        skillPool.clear();
        skillPool.add(new Slap(ch));
        skillPool.add(new Tribadism(ch));
        skillPool.add(new PussyGrind(ch));
        skillPool.add(new Slap(ch));
        skillPool.add(new ArmBar(ch));
        skillPool.add(new Blowjob(ch));
        skillPool.add(new Cunnilingus(ch));
        skillPool.add(new Escape(ch));
        skillPool.add(new Flick(ch));
        skillPool.add(new ToggleKnot(ch));
        skillPool.add(new LivingClothing(ch));
        skillPool.add(new LivingClothingOther(ch));
        skillPool.add(new Engulf(ch));
        skillPool.add(new CounterFlower(ch));
        skillPool.add(new Knee(ch));
        skillPool.add(new LegLock(ch));
        skillPool.add(new LickNipples(ch));
        skillPool.add(new Maneuver(ch));
        skillPool.add(new Paizuri(ch));
        skillPool.add(new PerfectTouch(ch));
        skillPool.add(new Restrain(ch));
        skillPool.add(new Reversal(ch));
        skillPool.add(new LeechEnergy(ch));
        skillPool.add(new SweetScent(ch));
        skillPool.add(new Spank(ch));
        skillPool.add(new Stomp(ch));
        skillPool.add(new StandUp(ch));
        skillPool.add(new WildThrust(ch));
        skillPool.add(new SuckNeck(ch));
        skillPool.add(new Tackle(ch));
        skillPool.add(new Taunt(ch));
        skillPool.add(new Trip(ch));
        skillPool.add(new Whisper(ch));
        skillPool.add(new Kick(ch));
        skillPool.add(new PinAndBlow(ch));
        skillPool.add(new PinningPaizuri(ch));
        skillPool.add(new Footjob(ch));
        skillPool.add(new FootPump(ch));
        skillPool.add(new HeelGrind(ch));
        skillPool.add(new Handjob(ch));
        skillPool.add(new Squeeze(ch));
        skillPool.add(new Nurple(ch));
        skillPool.add(new Finger(ch));
        skillPool.add(new Aphrodisiac(ch));
        skillPool.add(new Lubricate(ch));
        skillPool.add(new Dissolve(ch));
        skillPool.add(new Sedate(ch));
        skillPool.add(new Tie(ch));
        skillPool.add(new Masturbate(ch));
        skillPool.add(new Piston(ch));
        skillPool.add(new Grind(ch));
        skillPool.add(new Thrust(ch));
        skillPool.add(new UseDildo(ch));
        skillPool.add(new UseOnahole(ch));
        skillPool.add(new UseCrop(ch));
        skillPool.add(new Carry(ch));
        skillPool.add(new Tighten(ch));
        skillPool.add(new ViceGrip(ch));
        skillPool.add(new HipThrow(ch));
        skillPool.add(new SpiralThrust(ch));
        skillPool.add(new Bravado(ch));
        skillPool.add(new Diversion(ch));
        skillPool.add(new Undress(ch));
        skillPool.add(new StripSelf(ch));
        skillPool.add(new StripTease(ch));
        skillPool.add(new Sensitize(ch));
        skillPool.add(new EnergyDrink(ch));
        skillPool.add(new Strapon(ch));
        skillPool.add(new AssFuck(ch));
        skillPool.add(new Turnover(ch));
        skillPool.add(new Tear(ch));
        skillPool.add(new Binding(ch));
        skillPool.add(new Bondage(ch));
        skillPool.add(new WaterForm(ch));
        skillPool.add(new DarkTendrils(ch));
        skillPool.add(new Dominate(ch));
        skillPool.add(new Illusions(ch));
        skillPool.add(new Glamour(ch));
        skillPool.add(new LustAura(ch));
        skillPool.add(new MagicMissile(ch));
        skillPool.add(new Masochism(ch));
        skillPool.add(new NakedBloom(ch));
        skillPool.add(new ShrinkRay(ch));
        skillPool.add(new SpawnFaerie(ch, Ptype.fairyfem));
        skillPool.add(new SpawnImp(ch, Ptype.impfem));
        skillPool.add(new SpawnFaerie(ch, Ptype.fairymale));
        skillPool.add(new SpawnImp(ch, Ptype.impmale));
        skillPool.add(new SpawnFGoblin(ch, Ptype.fgoblin));
        skillPool.add(new SpawnSlime(ch));
        skillPool.add(new StunBlast(ch));
        skillPool.add(new Fly(ch));
        skillPool.add(new Command(ch));
        skillPool.add(new Obey(ch));
        skillPool.add(new OrgasmSeal(ch));
        skillPool.add(new DenyOrgasm(ch));
        skillPool.add(new Drain(ch));
        skillPool.add(new LevelDrain(ch));
        skillPool.add(new StoneForm(ch));
        skillPool.add(new FireForm(ch));
        skillPool.add(new Defabricator(ch));
        skillPool.add(new TentaclePorn(ch));
        skillPool.add(new Sacrifice(ch));
        skillPool.add(new Frottage(ch));
        skillPool.add(new FaceFuck(ch));
        skillPool.add(new VibroTease(ch));
        skillPool.add(new TailPeg(ch));
        skillPool.add(new CommandDismiss(ch));
        skillPool.add(new CommandDown(ch));
        skillPool.add(new CommandGive(ch));
        skillPool.add(new CommandHurt(ch));
        skillPool.add(new CommandInsult(ch));
        skillPool.add(new CommandMasturbate(ch));
        skillPool.add(new CommandOral(ch));
        skillPool.add(new CommandStrip(ch));
        skillPool.add(new CommandStripPlayer(ch));
        skillPool.add(new CommandUse(ch));
        skillPool.add(new ShortCircuit(ch));
        skillPool.add(new IceForm(ch));
        skillPool.add(new Barrier(ch));
        skillPool.add(new CatsGrace(ch));
        skillPool.add(new Charm(ch));
        skillPool.add(new Tempt(ch));
        skillPool.add(new EyesOfTemptation(ch));
        skillPool.add(new TailJob(ch));
        skillPool.add(new FaceSit(ch));
        skillPool.add(new Smother(ch));
        skillPool.add(new BreastSmother(ch));
        skillPool.add(new MutualUndress(ch));
        skillPool.add(new Surrender(ch));
        skillPool.add(new ReverseFuck(ch));
        skillPool.add(new ReverseCarry(ch));
        skillPool.add(new ReverseFly(ch));
        skillPool.add(new CounterDrain(ch));
        skillPool.add(new CounterRide(ch));
        skillPool.add(new CounterPin(ch));
        skillPool.add(new ReverseAssFuck(ch));
        skillPool.add(new Nurse(ch));
        skillPool.add(new Suckle(ch));
        skillPool.add(new UseDraft(ch));
        skillPool.add(new ThrowDraft(ch));
        skillPool.add(new ReverseAssFuck(ch));
        skillPool.add(new FondleBreasts(ch));
        skillPool.add(new Fuck(ch));
        skillPool.add(new Kiss(ch));
        skillPool.add(new Struggle(ch));
        skillPool.add(new Tickle(ch));
        skillPool.add(new Wait(ch));
        skillPool.add(new Bluff(ch));
        skillPool.add(new StripTop(ch));
        skillPool.add(new StripBottom(ch));
        skillPool.add(new Shove(ch));
        skillPool.add(new Recover(ch));
        skillPool.add(new Straddle(ch));
        skillPool.add(new ReverseStraddle(ch));
        skillPool.add(new Stunned(ch));
        skillPool.add(new Distracted(ch));
        skillPool.add(new PullOut(ch));
        skillPool.add(new ThrowDraft(ch));
        skillPool.add(new UseDraft(ch));
        skillPool.add(new TentacleRape(ch));
        skillPool.add(new Anilingus(ch));
        skillPool.add(new UseSemen(ch));
        skillPool.add(new Invitation(ch));
        skillPool.add(new SubmissiveHold(ch));
        skillPool.add(new BreastGrowth(ch));
        skillPool.add(new CockGrowth(ch));
        skillPool.add(new BreastRay(ch));
        skillPool.add(new FootSmother(ch));
        skillPool.add(new FootWorship(ch));
        skillPool.add(new BreastWorship(ch));
        skillPool.add(new CockWorship(ch));
        skillPool.add(new PussyWorship(ch));
        skillPool.add(new SuccubusSurprise(ch));
        skillPool.add(new TemptressHandjob(ch));
        skillPool.add(new TemptressBlowjob(ch));
        skillPool.add(new TemptressTitfuck(ch));
        skillPool.add(new TemptressRide(ch));
        skillPool.add(new TemptressStripTease(ch));
        skillPool.add(new Blindside(ch));
        skillPool.add(new LeechSeed(ch));
        skillPool.add(new Beg(ch));
        skillPool.add(new Cowardice(ch));
        skillPool.add(new Dive(ch));
        skillPool.add(new Offer(ch));
        skillPool.add(new ShamefulDisplay(ch));
        skillPool.add(new Stumble(ch));
        skillPool.add(new TortoiseWrap(ch));
        skillPool.add(new FaerieSwarm(ch));
        skillPool.add(new DarkTalisman(ch));
        skillPool.add(new HeightenSenses(ch));
        skillPool.add(new LewdSuggestion(ch));
        skillPool.add(new Suggestion(ch));
        skillPool.add(new ImbueFetish(ch));
        skillPool.add(new AssJob(ch));
        skillPool.add(new TailSuck(ch));
        skillPool.add(new ToggleSlimeCock(ch));
        skillPool.add(new ToggleSlimePussy(ch));
        skillPool.add(new Spores(ch));
        skillPool.add(new EngulfedFuck(ch));
        skillPool.add(new Pray(ch));
        skillPool.add(new Prostrate(ch));
        skillPool.add(new DarkKiss(ch));
        skillPool.add(new SlimeMimicry(ch));
        skillPool.add(new MimicAngel(ch));
        skillPool.add(new MimicCat(ch));
        skillPool.add(new MimicDryad(ch));
        skillPool.add(new MimicSuccubus(ch));
        skillPool.add(new MimicWitch(ch));
        skillPool.add(new Parasite(ch));
        skillPool.add(new Bite(ch));
        skillPool.add(new PlaceBlindfold(ch));
        skillPool.add(new RipBlindfold(ch));
        skillPool.add(new ToggleBlindfold(ch));
        skillPool.add(new BunshinAssault(ch));
        skillPool.add(new BunshinService(ch));
        skillPool.add(new GoodnightKiss(ch));
        skillPool.add(new NeedleThrow(ch));
        skillPool.add(new StealClothes(ch));
        skillPool.add(new Substitute(ch));
        skillPool.add(new AttireShift(ch));
        skillPool.add(new CheapShot(ch));
        skillPool.add(new EmergencyJump(ch));
        skillPool.add(new Haste(ch));
        skillPool.add(new Rewind(ch));
        skillPool.add(new Unstrip(ch));
        skillPool.add(new WindUp(ch));
        skillPool.add(new ThrowSlime(ch));
        skillPool.add(new Edge(ch));
        skillPool.add(new SummonYui(ch));
        skillPool.add(new Simulacrum(ch));
        skillPool.add(new Divide(ch));
        skillPool.add(new PetThreesome(ch));
        skillPool.add(new ReversePetThreesome(ch));
        skillPool.add(new PetInitiatedThreesome(ch));
        skillPool.add(new PetInitiatedReverseThreesome(ch));
        skillPool.add(new FlyCatcher(ch));
        skillPool.add(new Honeypot(ch));
        skillPool.add(new TakeOffShoes(ch));
        skillPool.add(new LaunchHarpoon(ch));
        skillPool.add(new ThrowBomb(ch));
        skillPool.add(new RemoveBomb(ch));
        skillPool.add(new MagLock(ch));
        skillPool.add(new Collar(ch));
        skillPool.add(new HypnoVisorPlace(ch));
        skillPool.add(new HypnoVisorRemove(ch));
        skillPool.add(new StripMinor(ch));
        skillPool.add(new DemandArousal(ch));
        skillPool.add(new Embrace(ch));
        skillPool.add(new SuccubusNurse(ch));
        skillPool.add(new WingWrap(ch));
        skillPool.add(new ComeHither(ch));
        skillPool.add(new KiShout(ch));
        skillPool.add(new PressurePoint(ch));
        skillPool.add(new Deepen(ch));

        if (DebugFlags.isDebugOn(DebugFlags.DEBUG_SKILLS)) {
            skillPool.add(new SelfStun(ch));
        }
    }

    public static void learnSkills(Character c) {
        for (Skill skill : skillPool) {
            c.learn(skill);
        }
    }
}
